### PR TITLE
Add iconFile node to manifest

### PR DESCRIPTION
**Pull request by david-poindexter**
Fixes issue dazinator/DnnPackager#40

### CODE REVIEW

**Comment by dazinator** [comment]
Cheer for this!
Not sure why but there are 6 PR's created for this that look like duplicates.. i'm assuming I can just accept this one and close the duplicates? did you get trigger happy when clicking the create PR button or something :-)

**Comment by nvisionative** [comment]
Hmm, perhaps it is because I am still a GitHub newbie?  ;-)  There were many files that had to be updated for this, so when I edited each file (in browser), it prompted me to make a PR.  So I did, but tried to always reference Issue #43 to keep things organized.  Sorry if I caused issues.  I'd love to know how to do it the "right way" in the future!

**Comment by dazinator** [comment]
@nvisionative no worries, there is a bit of a learning curve to using Git (and GitHub!) but it's well worth it imho.

If you are working purely in GitHib, the flow would be:

1. First create your own "Fork" of the repository (press Fork button at top right of screen), this creates a copy of the repository under your own account.

2. Then, in your own Fork, switch to the "Development" branch, and then create a new branch and name it after the issue number you are addressing. You can do this all through the UI:

image

3. With your issue branch selected, make any changes you want to files until you are done.

4. One you are ready, and still within your fork, go to the Pull Requests screen and create a new PR

image

You will get to select your source branch, and the target branch you want to merge in to. You want to select your issue branch, and the "development" branch of my repository.

Then submit the PR.

We can then discuss and review the changes on the PR if necessary, or I'll just accept it if it's a trivial change. When I accept the PR it means it will merge the changes into the "development" branch.

Changes will accrue in the development branch, until I eventually push them to master, which generally, will form a new release.

I hope that helps! I know it seems like a lot.

Failing all of that, you can do what you did before, but before you change any files, switch to the "development" branch rather than doing it on master, and if it keeps asking you to create a PR for each change, you shouldn;t need too, if you already have 1 active ;)

**Comment by nvisionative** [comment]
@dazinator thank you so much for the detailed guidance.  That makes sense 100%!  We will do that next time for sure - cheers!  ;-)

**Pull request closed without merging**
