### PR TITLE
Add support for SPA and MVC module development

### PR DESCRIPTION
**Pull request by nvisionative**
Essentially the only thing that changes in the DNN manifest for SPA and MVC modules in DNN 8 are the controlSrc tags.  ASCX files are no longer the only options.  See the following for reference:

**SPA**
* https://github.com/jbrinkman/DNN8Templates/blob/master/src/DnnSpaModule/DnnSpaModule.dnn

**MVC**
* https://github.com/jbrinkman/DNN8Templates/blob/master/src/DnnMvcModule/DnnMvcModule.dnn

### CODE REVIEW

**Comment by dazinator** [comment]
Ah I see what you have done there.
Thank you for this.

**Comment by nvisionative** [comment]
You are very welcome.  I am stoked about your solution here.  Now we just need to get NuGet packages created for SPA and MVC scaffolding!  ;-)

**Comment by nvisionative** [comment]
Would you mind letting me know when this gets released?  I noticed in my testing last night that these changes must not have been made just yet.

**Comment by dazinator** [comment]
- This has now been released - release notes are here: https://github.com/dazinator/DnnPackager/releases/

 Sorry it didn't go out straight away, have been working on the next major version ;)

Thanks again for the PR!

**Comment by dazinator** [comment]
- have also [updated the blog post](http://darrelltunnell.net/blog/2015/12/01/dnnpackager-getting-started/) so that it shows the new manifest format.

**Comment by nvisionative** [comment]
No rush at all - was just curious to know when it is released.  Thanks man!  I have been talking up your solution within the DNN Community and quite a few people have showed interest for this approach.  Now we just need to see who can crank out a traditional, SPA and MVC package for the extra scaffolding.

**Comment by dazinator** [comment]
+10000 for spreading the word! ;)
Interestingly it looks like builds of DNN 8 are producing some additional NuGet packages - like an MVC one.. So perhaps some of the packages we need will be available soon for DNN8 atleast. If you get a moment you can see them here: (click login as guest): https://build.dnnsoftware.com/viewLog.html?buildId=326507&buildTypeId=bt929&tab=artifacts#!

**Comment by nvisionative** [comment]
You are welcome.  The MVC package you are seeing is simply a reference to *DotNetNuke.Web.Mvc.dll* (which would be needed for MVC development pattern.  So, unfortunately these new packages are not what they may have originally seemed to be (necessary nonetheless though).  ;-)

**Pull request merged**
